"""Generate generic character rules from Python's bundled Unicode names.

No business records, external identities, or network access are used. These are
approximate sound features, not a claim of linguistically exact transliteration.
The generated header is committed so inference needs only a C++17 compiler.
"""
import json
from pathlib import Path
import unicodedata


def main():
    vowels = {"A": "a", "AA": "a", "I": "i", "II": "i", "U": "u", "UU": "u",
              "E": "e", "EE": "e", "AI": "ai", "O": "o", "OO": "o", "AU": "au",
              "VOCALIC R": "ri", "VOCALIC RR": "ri", "VOCALIC L": "li", "VOCALIC LL": "li"}
    consonants = {"KA": "k", "KHA": "kh", "GA": "g", "GHA": "gh", "NGA": "n",
                  "CA": "ch", "CHA": "ch", "JA": "j", "JHA": "jh", "NYA": "n",
                  "TTA": "t", "TTHA": "th", "DDA": "d", "DDHA": "dh", "NNA": "n",
                  "TA": "t", "THA": "th", "DA": "d", "DHA": "dh", "NA": "n", "NNNA": "n",
                  "PA": "p", "PHA": "f", "BA": "b", "BHA": "bh", "MA": "m", "YA": "y",
                  "YYA": "y", "RA": "r", "RRA": "r", "LA": "l", "LLA": "l", "LLLA": "l",
                  "VA": "v", "SHA": "sh", "SSA": "sh", "SA": "s", "HA": "h", "QA": "k",
                  "KHHA": "kh", "GHHA": "g", "ZA": "z", "DDDHA": "r", "RHA": "r", "FA": "f"}
    scripts = {"DEVANAGARI", "BENGALI", "GURMUKHI", "GUJARATI", "ORIYA", "TAMIL", "TELUGU", "KANNADA", "MALAYALAM"}
    rows = []
    for code in range(0x900, 0xD80):
        name = unicodedata.name(chr(code), "")
        if not name or name.split()[0] not in scripts:
            continue
        text, kind = "", 0
        if "LETTER " in name:
            suffix = name.split("LETTER ")[1].replace("CANDRA ", "").replace("SHORT ", "")
            if suffix in vowels:
                text, kind = vowels[suffix], 1
            elif suffix in consonants:
                text, kind = consonants[suffix] + "a", 2
        elif "VOWEL SIGN " in name:
            suffix = name.split("VOWEL SIGN ")[1].replace("CANDRA ", "").replace("SHORT ", "")
            if suffix in vowels:
                text, kind = vowels[suffix], 3
        elif "VIRAMA" in name or "PULLI" in name:
            kind = 4
        elif "ANUSVARA" in name or "BINDI" in name or "TIPPI" in name:
            text, kind = "n", 1
        elif "VISARGA" in name:
            text, kind = "h", 1
        elif unicodedata.category(chr(code)) == "Nd":
            text, kind = str(unicodedata.digit(chr(code))), 1
        if kind:
            rows.append(f"    {{{code}, {{{json.dumps(text)}, {kind}}}}},")
    path = Path(__file__).with_name("transliteration_data.h")
    path.write_text("// Generated by generate_transliteration.py from Unicode character names.\n"
                    "// Types: independent, consonant, vowel mark, virama.\n"
                    "static const unordered_map<uint32_t,pair<string,int>> ROMAN_RULES = {\n"
                    + "\n".join(rows) + "\n};\n")
    print(f"Generated {len(rows)} character rules in {path}")


if __name__ == "__main__":
    main()
